apiVersion: v1
kind: ConfigMap
metadata:
  name: modelmonitor-config
  namespace: model-monitoring-system
data:
  inferenceLogger: |-
    {
        "containerImage": "javierdlrm/inference-logger:v1beta1"
    }
  job: |-
    {
        "containerImage": "javierdlrm/model-monitoring-job:v1beta1",
        "mainClass": "io.hops.ml.monitoring.job.Monitor",
        "mainApplicationFile": "local:///opt/spark/model-monitoring-job/job-1.0-SNAPSHOT.jar"
    }
