// +build !ignore_autogenerated

/*
Copyright 2020 Javier de la Rúa Martínez.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisSpec) DeepCopyInto(out *AnalysisSpec) {
	*out = *in
	out.Stats = in.Stats
	if in.Outliers != nil {
		in, out := &in.Outliers, &out.Outliers
		*out = new(SinkSpec)
		**out = **in
	}
	if in.Drift != nil {
		in, out := &in.Drift, &out.Drift
		*out = new(SinkSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisSpec.
func (in *AnalysisSpec) DeepCopy() *AnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(AnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvgSpec) DeepCopyInto(out *AvgSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvgSpec.
func (in *AvgSpec) DeepCopy() *AvgSpec {
	if in == nil {
		return nil
	}
	out := new(AvgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineSpec) DeepCopyInto(out *BaselineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineSpec.
func (in *BaselineSpec) DeepCopy() *BaselineSpec {
	if in == nil {
		return nil
	}
	out := new(BaselineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrSpec) DeepCopyInto(out *CorrSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrSpec.
func (in *CorrSpec) DeepCopy() *CorrSpec {
	if in == nil {
		return nil
	}
	out := new(CorrSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountSpec) DeepCopyInto(out *CountSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountSpec.
func (in *CountSpec) DeepCopy() *CountSpec {
	if in == nil {
		return nil
	}
	out := new(CountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CovSpec) DeepCopyInto(out *CovSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CovSpec.
func (in *CovSpec) DeepCopy() *CovSpec {
	if in == nil {
		return nil
	}
	out := new(CovSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistrSpec) DeepCopyInto(out *DistrSpec) {
	*out = *in
	if in.Bounds != nil {
		in, out := &in.Bounds, &out.Bounds
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistrSpec.
func (in *DistrSpec) DeepCopy() *DistrSpec {
	if in == nil {
		return nil
	}
	out := new(DistrSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSpec) DeepCopyInto(out *DriftSpec) {
	*out = *in
	if in.Wasserstein != nil {
		in, out := &in.Wasserstein, &out.Wasserstein
		*out = new(ThresholdBasedDriftSpec)
		**out = **in
	}
	if in.KullbackLeibler != nil {
		in, out := &in.KullbackLeibler, &out.KullbackLeibler
		*out = new(ThresholdBasedDriftSpec)
		**out = **in
	}
	if in.JensenShannon != nil {
		in, out := &in.JensenShannon, &out.JensenShannon
		*out = new(ThresholdBasedDriftSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSpec.
func (in *DriftSpec) DeepCopy() *DriftSpec {
	if in == nil {
		return nil
	}
	out := new(DriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceLoggerConfig) DeepCopyInto(out *InferenceLoggerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceLoggerConfig.
func (in *InferenceLoggerConfig) DeepCopy() *InferenceLoggerConfig {
	if in == nil {
		return nil
	}
	out := new(InferenceLoggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceLoggerSpec) DeepCopyInto(out *InferenceLoggerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceLoggerSpec.
func (in *InferenceLoggerSpec) DeepCopy() *InferenceLoggerSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceLoggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobConfig) DeepCopyInto(out *JobConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobConfig.
func (in *JobConfig) DeepCopy() *JobConfig {
	if in == nil {
		return nil
	}
	out := new(JobConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSpec) DeepCopyInto(out *JobSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSpec.
func (in *JobSpec) DeepCopy() *JobSpec {
	if in == nil {
		return nil
	}
	out := new(JobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSpec) DeepCopyInto(out *KafkaSpec) {
	*out = *in
	out.Topic = in.Topic
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSpec.
func (in *KafkaSpec) DeepCopy() *KafkaSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTopicSpec) DeepCopyInto(out *KafkaTopicSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTopicSpec.
func (in *KafkaTopicSpec) DeepCopy() *KafkaTopicSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaTopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxSpec) DeepCopyInto(out *MaxSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxSpec.
func (in *MaxSpec) DeepCopy() *MaxSpec {
	if in == nil {
		return nil
	}
	out := new(MaxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeanSpec) DeepCopyInto(out *MeanSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeanSpec.
func (in *MeanSpec) DeepCopy() *MeanSpec {
	if in == nil {
		return nil
	}
	out := new(MeanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinSpec) DeepCopyInto(out *MinSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinSpec.
func (in *MinSpec) DeepCopy() *MinSpec {
	if in == nil {
		return nil
	}
	out := new(MinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMonitor) DeepCopyInto(out *ModelMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMonitor.
func (in *ModelMonitor) DeepCopy() *ModelMonitor {
	if in == nil {
		return nil
	}
	out := new(ModelMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMonitorConfig) DeepCopyInto(out *ModelMonitorConfig) {
	*out = *in
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(JobConfig)
		**out = **in
	}
	if in.InferenceLogger != nil {
		in, out := &in.InferenceLogger, &out.InferenceLogger
		*out = new(InferenceLoggerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMonitorConfig.
func (in *ModelMonitorConfig) DeepCopy() *ModelMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(ModelMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMonitorList) DeepCopyInto(out *ModelMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMonitorList.
func (in *ModelMonitorList) DeepCopy() *ModelMonitorList {
	if in == nil {
		return nil
	}
	out := new(ModelMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMonitorSpec) DeepCopyInto(out *ModelMonitorSpec) {
	*out = *in
	in.Model.DeepCopyInto(&out.Model)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Storage.DeepCopyInto(&out.Storage)
	out.Job = in.Job
	out.InferenceLogger = in.InferenceLogger
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMonitorSpec.
func (in *ModelMonitorSpec) DeepCopy() *ModelMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ModelMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMonitorStatus) DeepCopyInto(out *ModelMonitorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMonitorStatus.
func (in *ModelMonitorStatus) DeepCopy() *ModelMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSchemasSpec) DeepCopyInto(out *ModelSchemasSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSchemasSpec.
func (in *ModelSchemasSpec) DeepCopy() *ModelSchemasSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSchemasSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(int)
		**out = **in
	}
	out.Schemas = in.Schemas
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	out.Trigger = in.Trigger
	in.Stats.DeepCopyInto(&out.Stats)
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(BaselineSpec)
		**out = **in
	}
	if in.Outliers != nil {
		in, out := &in.Outliers, &out.Outliers
		*out = new(OutlierSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Drift != nil {
		in, out := &in.Drift, &out.Drift
		*out = new(DriftSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutlierSpec) DeepCopyInto(out *OutlierSpec) {
	*out = *in
	if in.Descriptive != nil {
		in, out := &in.Descriptive, &out.Descriptive
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutlierSpec.
func (in *OutlierSpec) DeepCopy() *OutlierSpec {
	if in == nil {
		return nil
	}
	out := new(OutlierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PercSpec) DeepCopyInto(out *PercSpec) {
	*out = *in
	if in.Percentiles != nil {
		in, out := &in.Percentiles, &out.Percentiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PercSpec.
func (in *PercSpec) DeepCopy() *PercSpec {
	if in == nil {
		return nil
	}
	out := new(PercSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pow2SumSpec) DeepCopyInto(out *Pow2SumSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pow2SumSpec.
func (in *Pow2SumSpec) DeepCopy() *Pow2SumSpec {
	if in == nil {
		return nil
	}
	out := new(Pow2SumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkSpec) DeepCopyInto(out *SinkSpec) {
	*out = *in
	out.Kafka = in.Kafka
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkSpec.
func (in *SinkSpec) DeepCopy() *SinkSpec {
	if in == nil {
		return nil
	}
	out := new(SinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatSpec) DeepCopyInto(out *StatSpec) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(MaxSpec)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(MinSpec)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(CountSpec)
		**out = **in
	}
	if in.Sum != nil {
		in, out := &in.Sum, &out.Sum
		*out = new(SumSpec)
		**out = **in
	}
	if in.Pow2Sum != nil {
		in, out := &in.Pow2Sum, &out.Pow2Sum
		*out = new(Pow2SumSpec)
		**out = **in
	}
	if in.Distr != nil {
		in, out := &in.Distr, &out.Distr
		*out = new(DistrSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Avg != nil {
		in, out := &in.Avg, &out.Avg
		*out = new(AvgSpec)
		**out = **in
	}
	if in.Mean != nil {
		in, out := &in.Mean, &out.Mean
		*out = new(MeanSpec)
		**out = **in
	}
	if in.Stddev != nil {
		in, out := &in.Stddev, &out.Stddev
		*out = new(StddevSpec)
		**out = **in
	}
	if in.Perc != nil {
		in, out := &in.Perc, &out.Perc
		*out = new(PercSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cov != nil {
		in, out := &in.Cov, &out.Cov
		*out = new(CovSpec)
		**out = **in
	}
	if in.Corr != nil {
		in, out := &in.Corr, &out.Corr
		*out = new(CorrSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatSpec.
func (in *StatSpec) DeepCopy() *StatSpec {
	if in == nil {
		return nil
	}
	out := new(StatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StddevSpec) DeepCopyInto(out *StddevSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StddevSpec.
func (in *StddevSpec) DeepCopy() *StddevSpec {
	if in == nil {
		return nil
	}
	out := new(StddevSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Inference = in.Inference
	in.Analysis.DeepCopyInto(&out.Analysis)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SumSpec) DeepCopyInto(out *SumSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SumSpec.
func (in *SumSpec) DeepCopy() *SumSpec {
	if in == nil {
		return nil
	}
	out := new(SumSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdBasedDriftSpec) DeepCopyInto(out *ThresholdBasedDriftSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdBasedDriftSpec.
func (in *ThresholdBasedDriftSpec) DeepCopy() *ThresholdBasedDriftSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdBasedDriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSpec) DeepCopyInto(out *TriggerSpec) {
	*out = *in
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSpec.
func (in *TriggerSpec) DeepCopy() *TriggerSpec {
	if in == nil {
		return nil
	}
	out := new(TriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WindowSpec) DeepCopyInto(out *WindowSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WindowSpec.
func (in *WindowSpec) DeepCopy() *WindowSpec {
	if in == nil {
		return nil
	}
	out := new(WindowSpec)
	in.DeepCopyInto(out)
	return out
}
